server:
# tcp-ip порт, на котором будет доступен web-сервер
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
proxy-endpoints:
  file-storing: http://localhost:8081
  file-analysis: http://localhost:8082