server:
  port: 8082
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
remote-endpoints:
  file-storing-service: http://localhost:8081
  word-cloud-service: http://localhost:8083
picture-dir: pictures
db:
  url: "jdbc:postgresql://localhost:5432/postgres?encoding=UTF8"
  schema: bas_file_analysis
  user: baldina_a_s
  password: postgres
  maxPoolSize: 2
hash-algorithm: MD5